# Generated by Django 4.0.4 on 2022-05-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0002_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.album'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='collaborators',
            field=models.ManyToManyField(null=True, related_name='collaborate_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
