# Generated by Django 4.0.4 on 2022-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_item_image_alter_item_parent_alter_trip_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
