# Generated by Django 4.0.4 on 2022-06-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trip.album'),
        ),
    ]
