# Generated by Django 4.0.4 on 2022-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_trip_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_single',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
