# Generated by Django 4.0.4 on 2022-06-23 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_remove_item_is_single_remove_item_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 27, 4, 80251)),
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 27, 4, 80251)),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 27, 4, 80251)),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 27, 4, 80251)),
        ),
    ]
