# Generated by Django 4.0.4 on 2022-06-23 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_item_end_date_item_start_date_trip_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 37, 36, 970933)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 37, 36, 970933)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 37, 36, 970933)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 22, 37, 36, 970933)),
        ),
    ]
