# Generated by Django 4.0.4 on 2022-06-23 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_alter_item_end_date_alter_item_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 36, 27, 958237)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 36, 27, 958237)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 36, 27, 958237)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 36, 27, 958237)),
        ),
    ]
