# Generated by Django 4.0.4 on 2022-06-23 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_alter_item_end_date_alter_item_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 51, 46, 385241)),
        ),
        migrations.AlterField(
            model_name='item',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 51, 46, 385241)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 51, 46, 385241)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 51, 46, 385241)),
        ),
    ]
