# Generated by Django 4.0.4 on 2022-06-24 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_alter_item_end_date_alter_item_lat_alter_item_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 22, 6, 11, 200748)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 22, 6, 11, 200748)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 22, 6, 11, 200748)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 22, 6, 11, 200748)),
        ),
    ]
