# Generated by Django 4.0.4 on 2022-06-24 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_alter_item_description_alter_item_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 0, 17, 40, 325415)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 0, 17, 40, 325415)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 0, 17, 40, 323403)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 0, 17, 40, 323403)),
        ),
    ]
