# Generated by Django 4.0.4 on 2022-06-25 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0015_item_note_alter_item_end_date_alter_item_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 59, 54, 975998)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 59, 54, 975998)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 59, 54, 975998)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 59, 54, 975998)),
        ),
        migrations.CreateModel(
            name='AppreciatedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciated_users', to='trip.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciated_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
