# Generated by Django 4.0.4 on 2022-06-26 05:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0017_alter_item_end_date_alter_item_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 12, 32, 27, 878731)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 12, 32, 27, 878731)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 12, 32, 27, 876737)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 12, 32, 27, 876737)),
        ),
        migrations.CreateModel(
            name='AppreciatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciated_users', to='trip.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciated_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
