# Generated by Django 4.0.4 on 2022-06-27 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_alter_item_end_date_alter_item_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 21, 28, 54, 898745)),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 21, 28, 54, 898745)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 21, 28, 54, 897748)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 21, 28, 54, 896725)),
        ),
    ]
