version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn post_service.wsgi:application'
    ports:
      - 8000:8000
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'